// <auto-generated />
using System;
using APIClient.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIClient.Migrations
{
    [DbContext(typeof(AsignacionContext))]
    partial class AsignacionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIClient.Infrastructure.Data.Entities.Asignacion", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasColumnType("varchar(75)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasColumnType("varchar(75)");

                    b.Property<int>("Asignar")
                        .HasColumnType("int");

                    b.Property<string>("CodApp")
                        .IsRequired()
                        .HasColumnType("varchar(75)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("varchar(75)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("varchar(75)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("varchar(75)");

                    b.Property<string>("RolInsourcing")
                        .IsRequired()
                        .HasColumnType("varchar(75)");

                    b.HasKey("id");

                    b.ToTable("Asignacion");
                });
#pragma warning restore 612, 618
        }
    }
}
