// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace APIClient
{
    public partial class Carga
    {
        public int IdCarga { get; set; }
        public int? IdPeriodo { get; set; }
        public string NombreCal { get; set; }
        public string MatriculaCal { get; set; }
        public string NombreChapter { get; set; }
        public string MatriculaChapter { get; set; }
        public string TipoPreper { get; set; }
        public string Empresa { get; set; }
        public string MatriculaUsuario { get; set; }
        public string ApellidopaternoUsuario { get; set; }
        public string ApellidomaternoUsuario { get; set; }
        public string NombreUsuario { get; set; }
        public string ChapterUo { get; set; }
        public int? MatriculaCaldInterface { get; set; }
        public DateTime? FechaCarga { get; set; }
    }
}